# Generated by Django 3.2.8 on 2021-10-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='clients',
            name='phone',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
